spring:
  kafka:
    consumer:
      auto-offset-reset: latest
#      auto-offset-reset: earliest
      group-id: streamer
      enable-auto-commit: true
    producer:
      client-id: streamer
    bootstrap-servers: ["${BROKER_LIST}"]
  application:
    name: streamer
  data:
    mongodb:
      uri: mongodb://${MONGO}/collector.pages
server:
  port: 18888

#根据设置的master.uri来决定部署模式是什么样的，这儿是用standalone模式，也可以运行在yarn上
collector.spark.master.uri: spark://${SPARK}:7077
collector.mongo.page: pages
collector.mongo.minute: minutes
collector.mongo.hour: hours
collector.mongo.day: days

streamer.kafka.minute: "streamer.minute"
streamer.hdfs.minute: "hdfs://${HDFS}/streamer/minute"

---

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}

