spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: streamer
    producer:
      client-id: streamer
    bootstrap-servers: ["192.168.1.204:9092"]
  application:
    name: streamer
  data:
    mongodb:
      uri: mongodb://192.168.1.100:27020/collector.pages
server:
  port: 18888


collector.spark.master.uri: spark://192.168.1.204:7077
collector.mongo.page: pages
collector.mongo.minute: minutes
collector.mongo.hour: hours
collector.mongo.day: days

streamer.kafka.minute: "streamer.minute"

---

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}

