spring:
  kafka:
    consumer:
      auto-offset-reset: latest
#      auto-offset-reset: earliest
      group-id: streamer
      enable-auto-commit: true
    producer:
      client-id: streamer
    bootstrap-servers: ["${KAFKA}:9092"]
  application:
    name: streamer
  data:
    mongodb:
      uri: mongodb://${MONGO}:27020/collector.pages
server:
  port: 18888


collector.spark.master.uri: spark://${SPARK}:7077
collector.mongo.page: pages
collector.mongo.minute: minutes
collector.mongo.hour: hours
collector.mongo.day: days

streamer.kafka.minute: "streamer.minute"
streamer.hdfs.minute: "hdfs://${HDFS}:14000/streamer/minute"

---

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}

