spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: boot
    producer:
      client-id: boot
    bootstrap-servers: ["192.168.1.204:9092"]
  application:
    name: collector
server:
  port: 8888


collector.buffer.size: 1
#collector.spark.master.uri: http://192.168.1.204
---

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}

