spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: boot
    producer:
      client-id: boot
    bootstrap-servers: ["192.168.1.204:9092"]
  application:
    name: collector
server:
  port: 8888


---

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}

---
spring:
  profiles: integration
  cloud:
    consul:
      host: ${CONSUL_ADDRESS:192.168.1.100}
      port: ${CONSUL_PORT:8501}


---
spring:
  profiles: stable
  cloud:
    consul:
      host: ${CONSUL_ADDRESS:192.168.1.200}
      port: ${CONSUL_PORT:8501}