#可以看maven依赖中的spring autoconfig 包中的spring.factories文件中的KafkaConfig和MongoConfig
#在具体的配置类中可以看到相应的Template类和Properties类，Properties类中用到的属性的路径就是yml文件中的
spring:
  kafka:
    producer:
      client-id: collector
    bootstrap-servers: ["${BROKER_LIST}"]
  application:
    name: collector
  data:
    mongodb:
    #uri写到db层即可
      uri: mongodb://${MONGO}/collector

server:
#web接口对应的端口号
  port: ${WEB_PORT}

#页面浏览信息存放的mongo集合
collector.mongo.page: pages
#页面浏览信息存放的mongo集合
collector.mongo.option: options

kafka.topic.page: collector.page
kafka.topic.option: collector.option
---

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}

