spring:
  kafka:
    producer:
      client-id: collector
    bootstrap-servers: ["${KAFKA}:9092"]
  application:
    name: collector
  data:
    mongodb:
      uri: mongodb://${MONGO}:27020/collector.pages
server:
  port: 8888


collector.mongo.page: pages
---

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}

